version: '2'

volumes:

services:
  node:
    restart: always
    build:
      context: .
      args:
        NODE_ENV: production
    volumes:
      - .:/usr/app/
      - node_modules:/usr/app/node_modules
    depends_on:
    environment:
      - NODE_ENV=production
    ports:
    - "3000:3000"
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    links:
      - node
    volumes:
      - ./compose/nginx:/etc/nginx/conf.d
      - ./compose/certbot/conf:/etc/letsencrypt
      - ./compose/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./compose/certbot/conf:/etc/letsencrypt
      - ./compose/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
